name: Release
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - run: chmod +x ./gradlew

      - name: Update mod version
        uses: christian-draeger/write-properties@1.0.1
        with:
          path: "gradle.properties"
          property: "mod_version"
          value: ${{ github.event.release.tag_name }}

      - name: build
        run: ./gradlew build

      - name: Upload to github releases
        if: ${{ github.event_name == 'release' }}
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/libs/thermomix-${{ github.event.release.tag_name }}.jar
          asset_name: thermomix-${{ github.event.release.tag_name }}.jar
          asset_content_type: application/java-archive

      - name: publish to github packages
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: upload to curseforge
        continue-on-error: true
        run: ./gradlew curseforge
        env:
          CURSEFORGE_TOKEN: ${{ secrets.CURSEFORGE_TOKEN }}
          CHANGELOG: ${{ github.event.release.body }}

      - name: upload to modrinth
        continue-on-error: true
        run: ./gradlew modrinth
        env:
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
          CHANGELOG: ${{ github.event.release.body }}
